version: "3.8"
 
services:
    #insert database before building the simple microservices?

    # 6 simple microservices

    #port 5000
    delivery:
        image: <dockerid>/delivery:1.0
        restart: always
        environment:
            dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/delivery_db

    #port 5001
    driver:
        image: <dockerid>/driver:1.0
        restart: always
        environment:
            dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/driver

    #port 5002
    customer:
        image: <dockerid>/customer:1.0
        restart: always
        environment:
            dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/customer

    #port 5003        
    payment:
        image: <dockerid>/payment:1.0
        restart: always
        environment:
            dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/payment

    #port 5004        
    schedule:
        image: <dockerid>/schedule:1.0
        restart: always
        environment:
            dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/schedule_db
    
    #port 5005
    login:
        image: <dockerid>/login:1.0
        restart: always
        environment:
            dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/login

    # 5 Complex microservices

    #port 5104, but done first since it is needed by 5100
    schedule_driver:
        image: <dockerid>/ScheduleDriver:1.0
        depends_on:
        -schedule
        environment:
            scheduleURL: http://delivery:5004/schedule
    
    #port 5100
    process_order:
        image: <dockerid>/ProcessOrder:1.0
        depends_on:
        - delivery
        - driver
        - customer
        - payment
        - schedule
        - schedule_driver
        environment:
            deliveryURL: http://delivery:5000/delivery
            driverURL: http://driver:5001/driver
            customerURL: http://delivery:5002/customer
            paymentURL: http://payment:5003/payment
            scheduleURL: http://delivery:5004/schedule
            ScheduleDriverURL: http://delivery:5104/schedule_driver


    #port 5101
    driver_view_details:
        image: <dockerid>/DriverViewDetails:1.0
        depends_on:
        - delivery
        environment:
            deliveryURL: http://delivery:5000/delivery


    # port 5102
    customer_view_details:
        image: <dockerid>/CustomerViewDetails:1.0
        depends_on:
        - delivery
        - driver
        environment:
            deliveryURL: http://delivery:5000/delivery
            driverURL: http://driver:5001/driver

    #port 5103
    driver_complete_delivery:
        image: <dockerid>/DriverCompleteDelivery:1.0
        depends_on:
        - delivery
        - driver
        environment:
            deliveryURL: http://delivery:5000/delivery
            driverURL: http://driver:5001/driver

    #port 5105
    register_user:
        image: <dockerid>/RegisterUser:1.0
        depends_on:
            - login
            - customer
            - driver     #register a driver
            environment:
                loginURL: http://login:5005/login
                customerURL: http://customer:5002/customer
                driverURL: http://driver:5001/driver
